# fly.toml app configuration file generated for gmail-automation on 2025-02-12T08:33:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gmail-automation'
primary_region = 'nrt'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3000
min_machines_running = 1
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory = '1gb'
memory_mb = 1024
